CMS-440: data model and migrations
bcgov/bcparks-staff-portal pull request #22
Opened 2024-10-23 15:59 UTC by diego-oxd

### Jira Ticket

CMS-440
https://bcparksdigital.atlassian.net/browse/CMS-440

### Description
- added data model
- added sequelize-cli to manage DB migrations
- need to run `npx sequelize-cli db:migrate` to sync changes

2024-10-24 00:00 UTC, duncan-oxd commented
Cool! I guess we can get rid of the example models in db/models and the couple of places that are using the "DbRow" test model. If you don't get a chance, I can probably do that tomorrow. Might as well do it in this same branch.

2024-10-24 00:01 UTC, duncan-oxd commented
I just pushed a small commit to add a "migrate" npm script, so we can type `npm run migrate` and it will use the version of sequelize-cli installed in package.json 👍

2024-10-24 00:06 UTC, diego-oxd commented
> Cool! I guess we can get rid of the example models in db/models and the couple of places that are using the "DbRow" test model. If you don't get a chance, I can probably do that tomorrow. Might as well do it in this same branch.

Cool, I'll do it early tomorrow.

2024-10-24 00:14 UTC, duncan-oxd requested changes
Got a few questions and suggestions; forgive me for being clueless because I haven't used Sequelize before :P 

Too bad the models and the db schema aren't as tightly coupled as with Django. I think Sequelize is popular for being easy, but maybe it's "easy but not simple" 🤔 

It's not a requirement for this project if you think we should check out something else like Prisma, but it looks like it should do the trick. Let me know if you have concerns!

2024-10-24 00:14 UTC, duncan-oxd commented on backend/models/index.js
I don't have any experience with Sequelize myself, so I don't know if this is true, but I thought we could do the associations in the model files without needing this extra step. (Unless this makes it easier?)

Instead of an `associate` method in the model file, we would just import the associated models in the file and add a line like 

```js
ParkFeature.belongsTo(Park, { foreignKey: "parkId" });
```

Right after the class definition. Would that be easier?

2024-10-24 00:14 UTC, duncan-oxd commented on backend/config/config.js
I think the sequelize connection stuff is already set up in `/db/connection.js` - can we use that? Or is that only gonna be used by Express?

2024-10-24 00:36 UTC, diego-oxd commented on backend/models/index.js
That was my original plan too. But when you run the CLI command to create the migrations it creates the models using this syntax, and then you have to define the associations like this. 
To run something like 
`ParkFeature.belongsTo(Park, { foreignKey: "parkId" });` you'd still need to instantiate every model first like we're doing in index.js. So, I thought might as well just stay in the framework of what `sequelize-cli` suggests. 
We can talk about it tomorrow.

2024-10-24 00:38 UTC, diego-oxd commented on backend/config/config.js
When you run the migrate CLI command, it always expects this file to exist. I also tried to just reuse the existing sequelize connection. But seems like it requires this file. 

I'm also not familiar with sequelize, but if it's possible, it'd be great.

2024-10-24 20:57 UTC, duncan-oxd commented on backend/config/config.js
Just pushed some changes to organize this 👍

2024-10-28 19:02 UTC, duncan-oxd commented on backend/models/user.js
> +     */
I just realized these files are probably auto-generated... If the comment format disagrees with eslint, we can add an exception to the rules to ignore these.

2024-10-28 20:04 UTC, duncan-oxd approved these changes

2024-10-30 18:00 UTC, merged